### ISSUE TITLE
ske: Correctly handle windows paths

### ISSUE THREAD

**Issue by marekmaskarinec** [marekmaskarinec/tophat#119]
## Original issue:

[~mrms/tophat#21](https://todo.sr.ht/~mrms/tophat/21)

## Initial message:

doing something like `tophat -main tests\uit.um` doesn't work because we don't handle the Windows path format.

**Comment by skejeton** [comment]
I pushed windows path support, which includes support in resource paths, loading scripts via `-main`, and, most importantly in loading resources like fonts, images and audio. For the fonts images and audio the handling was already functional since normal C filesystem operations handle it by themselves, however I thought it would be a good consideration to make sure that person who wrote their tophat projects on Windows, loading with `\` slashes, can also be ran on Linux and other systems. If you think it's a good idea to remove it, say so.

**Comment by skejeton** [comment]
@marekmaskarinec I'm closing the issue for now, but feel free to re-open it if I should remove it from Linux.
