### ISSUE TITLE
'To menu' is not working

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#13]
Clicking the 'To menu` button in the space shooter examples immediately exits the program. I think this is because 'To menu' and 'Quit' both receive the same event.

A 'professional' solution would be, for example, to construct an event queue independently of any event handlers. An event is propagated though a hierarchy of UI controls (and handlers) until one of the handlers returns `true`, which means that the event has been handled.

Perhaps, simpler approaches are also possible. Maybe you can fire a 'click' event on _releasing_ rather than _pressing_ a button. Thus, 'Quit' will never catch a 'To menu' event because it will never see the whole push-release sequence intended for 'To menu'.

**Comment by marekmaskarinec** [comment]
Exactly, what is happening is, that the two buttons are located in the same place, so when you press the `to menu` button, the scene changes faster, than you release the button. An easy (although hacky) fix for this would be initializing buttons with pressed value true. Then justpressed won't be true, since pressed was already true. I will probably implement a release event though, but now I'm working on tilemaps, so it will take a while.

**Comment by marekmaskarinec** [comment]
Another solution is to add resetinput function, that would memset the `pressed` and `justpressed` arrays to 0. User would have to run that himself though, since I refuse to do engine handled scene switching.

**Comment by marekmaskarinec** [comment]
Fixed in e3cac81
