### ISSUE TITLE
Adding RAIDER to tophat examples

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#16]
RAIDER seems to have a more interesting gameplay than the space shooter. Will you consider updating RAIDER to the latest version of tophat (with newer features such as UI controls) and adding it to your standard set of examples? I think it's a good idea to have a "reference game" implemented with tophat -- a game interesting both for playing and demonstrating tophat features.

**Comment by marekmaskarinec** [comment]
I don't think, raider should be used as an example. Is is a better game than space shooter? Absolutely, but it's codebase is too big and not clean to be used as an example. When I was making raider, I was still figuring out, how to structure games properly (that's why there was the circular imports issue). I think, I will add a link to the readme, but it shouldn't be a separate example.
