### ISSUE TITLE
Pseudo 3D in tophat?

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#36]
Some games are known for their 2D graphics with a "pseudo 3D" effect. To achieve this, one at least needs to have game field cells (and also terrain texture tiles) rotated 45 deg and shrinked vertically to simulate an isometric projection, though without a "true" perspective. Does tophat support this?

Here are two examples I remember from my childhood:
![image](https://user-images.githubusercontent.com/52492460/139555346-0ff4dbbf-4d12-4aaa-8f36-f81df7aa77a8.png)
![image](https://user-images.githubusercontent.com/52492460/139555379-5b72b543-d75d-4d0d-8614-cb4429aadffc.png)

**Comment by marekmaskarinec** [comment]
I think there are two parts to this. One is having properly oriented tiles and other is actually rendering them. Rendering them is possible using `image.Image.draw`.

Currently, tophat can't oriented the tiles. Solution would be to load the tiles already oriented. A way of adding this functionality is to add another image drawing function that takes a quad instead of a transform.

I don't think support for these kind of games should be built into the engine. Can I close this?

**Comment by vtereshkov** [comment]
@marekmaskarinec Yes, I understand.
