### ISSUE TITLE
Tetris example: various defects

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/tophat#88]
@skejeton 

**Unclear goals**. To be honest, I don't understand how to play this kind of tetris with three different rotation keys, stashing, etc. I did not manage to earn any score. Ultimately I rewrote it into a conventional tetris for my personal needs.

**Unreliable controls.** The current logic does not guarantee a visible response to every key hit. A better, though still not perfect, approach is something like
```
	if input.isJustPressed(input.key_left) {
		dx = -1
	} else if input.isPressed(input.key_left) {
		dx -= 0.01 * th.delta
	} else if input.isJustPressed(input.key_right) {
		dx = 1
	} else if input.isPressed(input.key_right) {
		dx += 0.01 * th.delta
	} else {
		dx = 0
	}

	if fabs(dx) > 0.99 {
		prev := x
		x += dx
		if invalid() {
			x = prev
		}
		dx = 0
	}
```  
**Unreliable placement detection.** The current timer-based logic allows the player to make a piece slide horizontally by continuosly pressing the left and right arrow keys after the piece has already fallen and should not move any longer. A simple boolean flag is preferred:
```
fn update*() {
	prev := y
	y += ...
	if invalid() {
		toBePlaced = true
		y = prev
	}
...
}
...
	if falling_piece.toBePlaced {
		place()
	}
```
**Crazy text causing an overflow.** This line causes infinitely growing oscillations if `dt > 0.01`, which is always the case on my machine:
```
entry.y += (py-entry.y)*dt*100
```
A more reliable solution is just
```
entry.y += (py-entry.y)*0.1
```

**Comment by skejeton** [comment]
> Unclear goals. To be honest, I don't understand how to play this kind of tetris with three different rotation keys, stashing, etc. I did not manage to earn any score. Ultimately I rewrote it into a conventional tetris for my personal needs.

To be fair this Tetris clone is intended to emulate modern Tetris, they have stashes, 3 ways to rotate (90, -90, 180), and a "kick table" for t-spins and such. So the goal is really games like Tetris99 or TetrIO, I added the most basic features.

> Unreliable controls. The current logic does not guarantee a visible response to every key hit. A better, though still not perfect, approach is something like

I agree with the controls. Honestly I couldn't figure out what's wrong with controls, they felt weird, but I think you pointed out correctly that it's kinda "linear".

> Unreliable placement detection. The current timer-based logic allows the player to make a piece slide horizontally by continuosly pressing the left and right arrow keys after the piece has already fallen and should not move any longer. A simple boolean flag is preferred:

It's intentionally timer-based, since it's trying to replicate modern Tetris, where you would perform sequences of T-spins and other kicks with something like I piece, the pieces can't be placed immediately because it would make it impossible for players to perform these tricks. The timer is indeed broken though, I should have a timeout or any sort of way to prevent players from holding on forever, albeit doesn't change the gameplay much.

> Crazy text causing an overflow. This line causes infinitely growing oscillations if dt > 0.01, which is always the case on my machine:

As for dt. I initially had a constant but I decided to use the delta time thing, I think i would've been better off clamping it, but I agree it's broken, because on my PC vsync is turned off it didn't happen to me. 


To be fair, I wrote this code 8 months ago and just refurnished a few weeks ago to make it somewhat presentable. There's definitely a room for improvement. Thank you for the insightful review.

**Comment by vtereshkov** [comment]
@skejeton I guess I have never played "modern" tetris and don't even know what a T-spin is :)

**Comment by skejeton** [comment]
It's something like this, I performed it quite poorly but you get the idea :P
![Peek 2022-08-31 15-58](https://user-images.githubusercontent.com/27076041/187683361-752fbf4b-cbb3-470b-a39e-626e767723e0.gif)

I think it'll be worth adding a classic mode that plays like the NES Tetris though.

**Comment by marekmaskarinec** [comment]
Can this be closed?

**Comment by vtereshkov** [comment]
> Can this be closed?

@skejeton ?

**Comment by skejeton** [comment]
Yeah sure, however I still do think that I need to improve the Tetris example.. I'll definitely give it some more time maybe during weekend to polish it up, I don't really like presenting half baked products :smiling_face_with_tear:
